version: '3'
networks:
  pulsar:
    driver: bridge
  sidecar:
    driver: bridge
services:

# Pulsar full
  pulsar:
    image: apachepulsar/pulsar:3.2.0
    container_name: pulsar
    profiles: ["full"]
    restart: on-failure
    ports:
      - "6650:6650"
      - "8080:8080"
    command: ["bin/pulsar", "standalone"]
